// <auto-generated />
using Amaral.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amaral.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707183333_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amaral.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Books full of excitement and adventure.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science fiction books exploring futuristic concepts.",
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books delving into historical events and figures.",
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stories involving exciting and risky experiences.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Works featuring magical or supernatural elements, often set in imaginary worlds.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Stories designed to provoke excitement and suspense.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fiction intended to scare, unsettle, or horrify the reader.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Focuses on romantic relationships between characters.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A detailed description of a person's life.",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Light-hearted stories designed to amuse and entertain.",
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("Amaral.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ListPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Price100")
                        .HasColumnType("double precision");

                    b.Property<double>("Price50")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Kevin Hall",
                            Description = "Elara, a young warrior, must uncover her past and fight ancient darkness. In a world of myths and magic, she forges alliances to restore balance and save her realm.",
                            ISBN = "SWD9999001",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Shadows of Eternity"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sarah Davis",
                            Description = "When a reclusive artist becomes the sole witness to a murder, she must navigate a web of secrets and lies. As danger closes in, she discovers her art holds the key to unmasking the killer.",
                            ISBN = "CAW777777701",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Silent Witness"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sarah Davis",
                            Description = "Haunted by eerie whispers, a troubled woman returns to her childhood home. As she uncovers buried secrets, she must confront her darkest fears to escape a malevolent force from her past.",
                            ISBN = "RITO5555501",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Whispers in the Dark"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sarah Davis",
                            Description = "In the aftermath of war, a historian uncovers letters that reveal a forgotten love story. As she delves deeper, she finds parallels to her own life and must reconcile the past with the present.",
                            ISBN = "WS3333333301",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Echoes of the Past"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Steven Robinson",
                            Description = "Unlock your full potential with Creativity. This inspiring guide explores innovative techniques, exercises, and insights from successful creatives to help you ignite your imagination and transform your ideas into reality.",
                            ISBN = "JU458558999",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Creativity"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Nicole Martinez",
                            Description = "Join Liora, a young mage, on an epic quest to balance darkness and light in her war-torn realm. Facing mythical beasts and powerful sorcery, she discovers the true strength of her spirit and the magic within.",
                            ISBN = "FOT000000001",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "A Journey Through Shadows and Light"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jennifer Young",
                            Description = "When a renowned journalist returns to her hometown, she uncovers long-buried emotions and a lost love. As she navigates past and present, she must decide if she’s willing to risk everything for a second chance at happiness.",
                            ISBN = "YOT000000968",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Secrets of the Heart"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Steven Robinson",
                            Description = "A daring astronaut leads a team on a groundbreaking mission to an uncharted planet. Facing alien landscapes and unknown dangers, they must rely on their wits and each other to survive and uncover the planet's secrets.",
                            ISBN = "ZA0000003336",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Journey to the Unknown"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Ashley Clark",
                            Description = "A woman suffering from amnesia pieces together her past after finding a series of cryptic journal entries. As she unravels the mystery, she discovers a shocking truth that could change her life forever.",
                            ISBN = "KL1111225879",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Fragments of Memory"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Andrew Garcia",
                            Description = "In a realm torn by war, a young warrior inherits a legacy of valor and betrayal. As she seeks redemption for her fallen kingdom, she must navigate treacherous alliances and unearth ancient secrets to restore peace and honor to her people.",
                            ISBN = "PO0006792444",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "Legacy of the Fallen"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Laura White",
                            Description = "In a realm where magic is outlawed, a young sorcerer uncovers an ancient prophecy that could change the course of history. Pursued by dark forces, he must unravel the hidden truth to save his world from imminent destruction.",
                            ISBN = "WW9930000004",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "The Hidden Truth"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Stephanie Walker",
                            Description = "In a dystopian future, humanity faces extinction due to a mysterious plague. A scientist discovers a controversial method to regenerate human tissue, but as the experiments progress, ethical dilemmas and unforeseen consequences threaten to unravel the fabric of society",
                            ISBN = "EOU330698744",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "Flesh Start"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Brian Lewis",
                            Description = "Harmony Publishers chronicles the remarkable journey of one of the publishing industry's most influential houses. From its humble beginnings in a small office to becoming a powerhouse in literature, Harmony Publishers has consistently championed innovation, quality, and diversity in its catalog.",
                            ISBN = "AAD555878800",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Harmony Publishers"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Michael Brown",
                            Description = "In the twilight of the Middle Ages, a noblewoman finds herself betrothed to a mysterious knight tasked with defending the kingdom's last frontier. As they navigate courtly intrigue and battlefield dangers, their initial mistrust turns to reluctant admiration and, eventually, forbidden love amidst the turmoil of war and honor.",
                            ISBN = "UUT000000997",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "The Last Frontier"
                        },
                        new
                        {
                            Id = 15,
                            Author = "James Anderson",
                            Description = "In a realm where ancient dragons threaten the balance of power, a young guardian must rise to protect her people. With a mystical artifact as her only weapon, she embarks on a quest fraught with peril and betrayal. Alongside unlikely allies, she discovers her true destiny as the savior of her world.",
                            ISBN = "KAA007778958",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Guardian"
                        },
                        new
                        {
                            Id = 16,
                            Author = "James Anderson",
                            Description = "Amidst rising darkness, the guardian faces a new quest to uncover the lost secrets of an ancient prophecy. With allies old and new, she must navigate treacherous landscapes and confront formidable foes to safeguard her realm from impending doom.",
                            ISBN = "AC0002378377",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Guardian II"
                        },
                        new
                        {
                            Id = 17,
                            Author = "S S Monson",
                            Description = "In the competitive world of high-stakes corporate espionage, a brilliant hacker finds herself at the center of a dangerous game. As she uncovers a web of deceit and betrayal reaching the highest echelons of power, she must race against time to expose the truth and evade capture by ruthless adversaries.",
                            ISBN = "OOU000589600",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Top"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Marissa Pullman",
                            Description = "In a bustling city, three young teachers embark on their careers, each facing unique challenges in the modern educational landscape. As they navigate classroom dynamics, bureaucratic hurdles, and personal growth, their passion for teaching and dedication to their students are put to the ultimate test.",
                            ISBN = "PPI500000014",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "New Educators"
                        },
                        new
                        {
                            Id = 19,
                            Author = "James Murdor",
                            Description = "Creative Business Your Own offers practical insights and strategies for aspiring entrepreneurs looking to launch and grow their own creative ventures. From crafting a unique brand identity to navigating digital marketing and fostering innovation, this guide equips readers with essential tools and inspiration to succeed in the competitive world of creative business",
                            ISBN = "LWS000069889",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Creative Business your Own"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Emma Mayers",
                            Description = "In a quaint seaside town, a charming mechanic known as The Bike Guy captures the heart of a free-spirited artist who has sworn off love. As they collaborate on restoring a classic motorcycle, sparks fly, revealing layers of vulnerability and passion beneath their initial friction. Together, they navigate past wounds and unexpected challenges, discovering that true love can be found where you least expect it.",
                            ISBN = "TTA000366947",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Bike Guy"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Patricia Kim",
                            Description = "In a world where appearances are everything, a hapless photographer accidentally captures a series of hilarious celebrity mishaps on film. As the photos go viral, chaos ensues as everyone involved tries to save face and navigate the absurdities of fame, revealing that what looks good on paparazzi photos isn't always what it seems.",
                            ISBN = "PPP000069000",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "Looks Good On Papar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
