// <auto-generated />
using Amaral.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Amaral.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmaralWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Books full of excitement and adventure.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science fiction books exploring futuristic concepts.",
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books delving into historical events and figures.",
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stories involving exciting and risky experiences.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Works featuring magical or supernatural elements, often set in imaginary worlds.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Stories designed to provoke excitement and suspense.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fiction intended to scare, unsettle, or horrify the reader.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Focuses on romantic relationships between characters.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A detailed description of a person's life.",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Light-hearted stories designed to amuse and entertain.",
                            Name = "Comedy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
